### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by lcoller** [spencermountain/efrt#12]
The project indicates that it is licensed under MIT, but includes no license file or copyright notice.  As the MIT license requires a copyright notice (2nd paragraph - The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.) It is not possible to comply with this license.  Please include in the repository a copy of the MIT license with an appropriate copyright.

**Comment by spencermountain** [comment]
thanks.
fixed in `2.2.2`
